### ISSUE TITLE
Extra "/" symbol in the link to the project

### ISSUE THREAD

**Issue by ASM-Development** [CrawlerCode/redmine-time-tracking#14]
If you click on the link from the project name (https://disk.yandex.ru/i/dU0LUmntH9bNdQ), there will be an extra "/" symbol in the link.
`https://site.ru//projects/126`
As a result, we have two characters "//".

**Comment by CrawlerCode** [comment]
Thank you for reporting this.

Normally it should not be a problem, but I have fixed it now. After saving the settings again, the url is updated and displayed correctly.
It will be available in the new version (`v1.16.0`)
