### ISSUE TITLE
Redmine URL cannot have a subdirectory

### ISSUE THREAD

**Issue by wang-fut** [CrawlerCode/redmine-time-tracking#18]
My redmine has an URL like "http://domain.name:port/redmine/"
When I enter my redmine's url into the settings. it tells me to "Enter a valid URL".
It is a valid URL...

Redmine: 4.2.3
Web Browser: Edge 120.0.2210.160
Redmine Time Tracking: 1.16.1

**Comment by CrawlerCode** [comment]
Thank you for reporting this bug.

I have fixed this issue and it will be released in the next version.
