### ISSUE TITLE
Submit to firefox addons

### ISSUE THREAD

**Issue by jle64** [CrawlerCode/redmine-time-tracking#21]
Hey,

This extension works fine with Firefox, requiring only a small change to the manifest (see below). Could you consider submitting it to addons.mozilla.org?

The only needed change is to replace:
```
    "background": {
        "service_worker": "background.js"
    },
```
by
```
    "background": {
        "scripts": ["background.js"]
    },
    "browser_specific_settings": {
        "gecko": {
            "id": "SOME_UNIQUE_ID@HERE",
            "strict_min_version": "124.0"
        }
    },
```
in the `manifest.json` file, replacing the id by a unique id.

If you don't want to submit it I can do it but I didn't want to do so without asking first.

Thanks,

**Comment by CrawlerCode** [comment]
This has been planned for some time, and I have also optimized the extension for Firefox in the past.

Now I built the extension for Firefox and submitted it to the Firefox-Store for review. 
It should be available here soon: https://addons.mozilla.org/de/firefox/addon/redmine-time-tracking

**Comment by jle64** [comment]
Ah nice, thanks.
