### ISSUE TITLE
Global ticket searching

### ISSUE THREAD

**Issue by ybbih** [CrawlerCode/redmine-time-tracking#22]
Hi,
I would like to request a feature that allows searching for tickets without filtering by a specific project. Currently, it's possible to search for tickets globally by clicking the magnifying glass icon next to a project and manually removing the project filter:
![Screenshot_3](https://github.com/user-attachments/assets/d4c06b16-0a2f-4f11-9711-540b6336a85a)
_____
![Screenshot_4](https://github.com/user-attachments/assets/ef59350e-e16f-4e32-886a-2aaf693e12cc)

Our support team frequently navigates through tickets across multiple projects, and having to remove the project filter manually each time is a bit inconvenient.

Thanks in advance!

**Comment by CrawlerCode** [comment]
This feature is already available. For the global search, you only need to press CTRL + K or CTRL + F
