### ISSUE TITLE
Context menu visibility

### ISSUE THREAD

**Issue by qsnewuser** [CrawlerCode/redmine-time-tracking#26]
### Browser

- [X] Chrome
- [ ] Firefox

### Extension version

1.20.1

### Redmine version

5.1.4 or 6.0.1 (I'm not an admin)

### Describe the bug

For some issues in the list the context menu is not fully visible. If I don't touch the scroll and do a right mouse click (open context menu) for the second issue in the list, I see only bottom of the menu.

### To Reproduce

1. Right click on the first issue in the list. You are getting the full context menu
![image](https://github.com/user-attachments/assets/e45bc21c-252f-4b08-8e1f-2c1355aedb93)

2. Right click on the second or third issue in the list (it happens randomly for the second or third)
3. You are getting only the bottom options of the context menu and the top options are hidden. The mouse cursor is treated as an end of the context menu
![image](https://github.com/user-attachments/assets/03452529-1f3b-4fba-b2a8-1c1adf0a75ae)

4. Scroll down a little bit and do the right click again on the same issue
5. You are getting the full context menu, that starts from the mouse cursor and down
![image](https://github.com/user-attachments/assets/9443d3d2-f348-483f-9bf2-1cddf7bae89c)

**Comment by CrawlerCode** [comment]
Thank you for reporting this bug.

I fixed the issue and release a new version (`v1.20.2`)
