### ISSUE TITLE
Add languages to the extension description

### ISSUE THREAD

**Issue by ASM-Development** [CrawlerCode/redmine-time-tracking#4]
On the extension description page https://chrome.google.com/webstore/detail/redmine-time-tracking/ldcanhhkffokndenejhafhlkapflgcjg, you need to add German and Russian languages.

https://yadi.sk/i/DmO2AsxQk3YMgA

**Comment by CrawlerCode** [comment]
Thanks for the hint. 

I have adjusted the extension to list all languages. It will be displayed as soon as Google is done with the review.
