### ISSUE TITLE
Add new elements to the translation file

### ISSUE THREAD

**Issue by ASM-Development** [CrawlerCode/redmine-time-tracking#6]
Add new elements to the translation file:

1. «h» — https://yadi.sk/i/qgLtmfBctIAwTA
2. «h» — https://yadi.sk/i/mco8fsSNnG6-FQ
3. «Version» — https://yadi.sk/i/BT_cRWdeu7DZHA

**Comment by CrawlerCode** [comment]
Thanks for the contribution.

If you wish, you can provide a Russian translation for the following messages:
```
"settings.info.version": "Version: {version}",
"format.hours": "{hours} h"
```

**Comment by Develop-FM** [comment]
I made the translation. Please add it to the language file «ru.json».

"settings.info.version": "Версия: {version}",
"format.hours": "{hours} ч"
