### ISSUE TITLE
Display the time not in fractions of an hour, but in the usual format

### ISSUE THREAD

**Issue by ASM-Development** [CrawlerCode/redmine-time-tracking#7]
For example, it's 30 minutes now, displayed as «0,5».
It will be much more convenient if 30 minutes is displayed everywhere as 0:30.

For example in these places:
1. https://yadi.sk/i/4BerZe3XoI4yMw
2. https://yadi.sk/i/2psHxL7LeCHfcQ

It is also possible to make a choice in the settings in which form to display the time as "0.5 (fractions)" or as "0:30 (usually)".
Each user will choose what is more convenient for him.
However, I think the "0:30 (usually)" format is the best choice.

**Comment by CrawlerCode** [comment]
Thank you for your idea.
I added the feature you requested. Now you can choose your preferred format.

![image](https://github.com/CrawlerCode/redmine-time-tracking/assets/41094392/5ea73fa1-cff2-455f-8980-276ee3fadcaf)

It will be available in the new version (`v1.15.0`)
